/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.gorsel.sinema.frm;

import com.gazi.gorsel.sinema.bll.CalisanBL;
import com.gazi.gorsel.sinema.bll.YetkiBL;
import com.gazi.gorsel.sinema.model.Calisan;
import com.gazi.gorsel.sinema.model.Yetki;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author emin
 */
public class frmCalisanEkle extends javax.swing.JFrame {

    /**
     * Creates new form frmCalisanEkle2
     */
    public frmCalisanEkle() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtKimlikNo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();
        btnKaydet = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cmbYetki = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Yeni Çalışan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adı Soyadı");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 47, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("T.C. Kimlik Numarası");
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 91, -1, -1));

        txtAd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 44, 138, -1));

        txtKullaniciAdi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtKullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 138, 138, -1));

        txtKimlikNo.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtKimlikNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 91, 138, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Şifre");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 188, -1, -1));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Kullanıcı Adı");
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 138, -1, -1));

        txtSifre.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 185, 138, -1));

        btnKaydet.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 114, -1));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Yetki");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 239, -1, -1));

        cmbYetki.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(cmbYetki, new org.netbeans.lib.awtextra.AbsoluteConstraints(251, 232, 138, 36));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/gorsel/sinema/img/calisan.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        CalisanBL cbl = new CalisanBL();
        YetkiBL ybl = new YetkiBL();
        Calisan c = new Calisan();
        c.setAd(txtAd.getText().trim());
        c.setKimlikNo(txtKimlikNo.getText().trim());
        c.setKullaniciAdi(txtKullaniciAdi.getText().trim());
        c.setYetkiid(ybl.YetkiIdGetir(cmbYetki.getSelectedItem().toString()));

        char[] pass = txtSifre.getPassword();
        String sifre = "";
        for (int i = 0; i < pass.length; i++) {
            sifre += pass[i];
        }
        c.setSifre(sifre);
        if (cbl.CalisanEkle(c) > 0) {
            JOptionPane.showMessageDialog(null, "Yeni çalışan eklendi.");
            txtAd.setText("");
            txtKimlikNo.setText("");
            txtKullaniciAdi.setText("");
            txtSifre.setText("");
        }
    }//GEN-LAST:event_btnKaydetActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        YetkiBL ytk = new YetkiBL();
        List<Yetki> list = ytk.YetkiListele();
        for (int i = 0; i < list.size(); i++) {
            cmbYetki.addItem(list.get(i).getYetki()
            );
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        frmLogin f = new frmLogin();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCalisanEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCalisanEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCalisanEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCalisanEkle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCalisanEkle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JComboBox<String> cmbYetki;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtAd;
    private javax.swing.JTextField txtKimlikNo;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
