/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.gorsel.sinema.frm;

import com.gazi.gorsel.sinema.bll.KategoriBL;
import com.gazi.gorsel.sinema.model.Kategori;
import javax.swing.JOptionPane;

/**
 *
 * @author emin
 */
public class frmKategoriEkle extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmKategoriEkle
     */
    public frmKategoriEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAdi = new javax.swing.JTextField();
        btnEkle = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Kategori Ekle");
        setMaximumSize(new java.awt.Dimension(750, 520));
        setMinimumSize(new java.awt.Dimension(750, 520));
        setPreferredSize(new java.awt.Dimension(750, 520));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Kategori Adı");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, -1));

        txtAdi.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 118, -1));

        btnEkle.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnEkle.setText("Kaydet");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });
        getContentPane().add(btnEkle, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 220, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/gorsel/sinema/img/kategori.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, 0, 910, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        KategoriBL kbl = new KategoriBL();
        Kategori k = new Kategori();
        k.setAd(txtAdi.getText());
        if (kbl.KategoriKayit(k) > 0) {
            JOptionPane.showMessageDialog(null, "Yeni kategori eklendi.");
            txtAdi.setText("");
        }
    }//GEN-LAST:event_btnEkleActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAdi;
    // End of variables declaration//GEN-END:variables
}
