/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.gorsel.sinema.frm;

import com.gazi.gorsel.sinema.bll.BiletBL;
import com.gazi.gorsel.sinema.bll.KoltukBL;
import com.gazi.gorsel.sinema.bll.SatisBL;
import com.gazi.gorsel.sinema.model.Bilet;
import com.gazi.gorsel.sinema.model.Film;
import com.gazi.gorsel.sinema.model.Koltuk;
import com.gazi.gorsel.sinema.model.KoltukMod;
import com.gazi.gorsel.sinema.model.Salon;
import com.gazi.gorsel.sinema.model.Satis;
import com.gazi.gorsel.sinema.model.Seans;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author emin
 */
public class frmKoltuk extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmKoltuk
     */
    Salon salon;
    Seans seans;
    String date;
    Film film;
    List<Koltuk> secilen = new ArrayList<>();

    public frmKoltuk() {
        initComponents();
    }

    public frmKoltuk(String dt, Salon sln, Seans sns, Film f) {
        initComponents();
        salon = sln;
        seans = sns;
        date = dt;
        film = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        btnSatisYap = new javax.swing.JButton();
        btnDolu = new javax.swing.JButton();
        btnSecilebilir = new javax.swing.JButton();
        btnSecili = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("Koltuk Seçimi");
        setToolTipText("");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formİnternalFrameOpened(evt);
            }
        });

        btnSatisYap.setText("Satış Yap");
        btnSatisYap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSatisYapActionPerformed(evt);
            }
        });

        btnDolu.setEnabled(false);

        btnSecilebilir.setPreferredSize(new java.awt.Dimension(50, 50));

        jLabel1.setText("Seçilebilir");

        jLabel2.setText("Seçilen");

        jLabel3.setText("Dolu");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addContainerGap(693, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDolu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSecili, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSecilebilir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnSatisYap)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addContainerGap())
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSatisYap)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnSecilebilir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnSecili, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)))
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnDolu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formİnternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formİnternalFrameOpened
        LoadKoltuk();
        btnSecilebilir.setBackground(Color.CYAN);
        btnSecili.setBackground(Color.green);
    }//GEN-LAST:event_formİnternalFrameOpened

    private void btnSatisYapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSatisYapActionPerformed
        Satis s = new Satis();
        Bilet b = new Bilet();
        KoltukMod km = new KoltukMod();
        SatisBL sbl = new SatisBL();
        BiletBL bbl = new BiletBL();
        KoltukBL kbl = new KoltukBL();
        frmMain f = new frmMain();
        s.setCalisanId(f.calisanId);
        s.setTutar(film.getFiyat() * secilen.size());
        s.setTarih(date);
        int id = sbl.SatisYap(s);
        int sonuc = 0;
        for (int i = 0; i < secilen.size(); i++) {
            b.setFilmId(film.getId());
            b.setSeansId(seans.getId());
            b.setKoltukId(secilen.get(i).getId());
            b.setSatisId(id);
            sonuc += bbl.BiletKayit(b);
            km.setKoltukId(secilen.get(i).getId());
            km.setSeansId(seans.getId());
            km.setTarih(date);
            km.setDolu(true);
            kbl.KoltukDoldur(km);
        }
        JOptionPane.showMessageDialog(null, sonuc + " bilet satıldı.");
        LoadKoltuk();
    }//GEN-LAST:event_btnSatisYapActionPerformed

    public void LoadKoltuk() {
        KoltukBL kbl = new KoltukBL();
        int sayac = 0;
        List<Koltuk> list = kbl.KoltukGetir(salon.getId());
        for (int i = 0; i < salon.getSira(); i++) {
            for (int j = 0; j < salon.getGenislik(); j++) {
                JButton btn = new JButton();
                btn.setBounds(j * 50 + 50, i * 50 + 50, 50, 50);
                btn.setText(String.valueOf((char) (65 + i)) + (j + 1));
                btn.setName(String.valueOf(list.get(sayac).getId()));
                btn.setBackground(Color.CYAN);
                if (kbl.KoltukDoluMu(Integer.parseInt(btn.getName()), seans.getId(), date)) {
                    btn.setEnabled(false);
                }
                btn.addActionListener((ActionEvent e) -> {
                    Koltuk k = new Koltuk();
                    if (btn.getBackground() == Color.CYAN) {
                        k.setId(Integer.parseInt(btn.getName()));
                        k.setKoltukNo(btn.getText());
                        k.setSalonId(salon.getId());
                        btn.setBackground(Color.green);
                        secilen.add(k);
                    } else if (btn.getBackground() == Color.green) {
                        k.setId(Integer.parseInt(btn.getName()));
                        k.setKoltukNo(btn.getText());
                        k.setSalonId(salon.getId());
                        btn.setBackground(Color.CYAN);
                        secilen.remove(k);
                    }
                });
                pnlMain.add(btn);
                if (sayac < list.size() - 1) {
                    sayac++;
                }
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDolu;
    private javax.swing.JButton btnSatisYap;
    private javax.swing.JButton btnSecilebilir;
    private javax.swing.JButton btnSecili;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlMain;
    // End of variables declaration//GEN-END:variables
}
