/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.gorsel.sinema.frm;

import com.gazi.gorsel.sinema.bll.CalisanBL;
import com.gazi.gorsel.sinema.model.Calisan;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author emin
 */
public class frmLogin extends javax.swing.JFrame {

    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
    }

    public void GirisYap() {
        Calisan c = new Calisan();
        CalisanBL cbl = new CalisanBL();
        c.setKullaniciAdi(txtKullaniciAdi.getText().trim());
        char[] pass = txtSifre.getPassword();
        String sifre = "";
        for (int i = 0; i < pass.length; i++) {
            sifre += pass[i];
        }
        c.setSifre(sifre);
        int id = cbl.GirisYap(c);
        int yetkiid = cbl.GirisYapanIdGetir(id);
        if (id > 0) {
            JOptionPane.showMessageDialog(null, "Giriş başarılı. Yönlendiriliyorsunuz...");
            frmMain f = new frmMain(id, yetkiid);
            f.setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Kullanıcı adı veya şifre hatalı. Lütfen tekrar deneyiniz.");
            txtKullaniciAdi.setText("");
            txtSifre.setText("");
            txtKullaniciAdi.requestFocus();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnGiris = new javax.swing.JButton();
        txtKullaniciAdi = new javax.swing.JTextField();
        txtSifre = new javax.swing.JPasswordField();
        btnKayit = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Giriş");
        setMaximumSize(new java.awt.Dimension(600, 380));
        setMinimumSize(new java.awt.Dimension(600, 380));
        setPreferredSize(new java.awt.Dimension(606, 381));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel1.setText("Kullanıcı Adı");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 100, 14));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 17)); // NOI18N
        jLabel2.setText("Şifre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, -1));

        btnGiris.setBackground(new java.awt.Color(204, 0, 204));
        btnGiris.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnGiris.setText("Giriş");
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });
        getContentPane().add(btnGiris, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 210, -1));

        txtKullaniciAdi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKullaniciAdiKeyTyped(evt);
            }
        });
        getContentPane().add(txtKullaniciAdi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 130, 25));

        txtSifre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSifreKeyTyped(evt);
            }
        });
        getContentPane().add(txtSifre, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 130, 25));

        btnKayit.setBackground(new java.awt.Color(204, 0, 204));
        btnKayit.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnKayit.setText("Kayıt Ol");
        btnKayit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKayitActionPerformed(evt);
            }
        });
        getContentPane().add(btnKayit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 210, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/gorsel/sinema/img/giris.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        GirisYap();
    }//GEN-LAST:event_btnGirisActionPerformed

    private void btnKayitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKayitActionPerformed
        frmCalisanEkle f = new frmCalisanEkle();
        f.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKayitActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_formWindowOpened

    private void txtKullaniciAdiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKullaniciAdiKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            txtSifre.requestFocus();
        }
    }//GEN-LAST:event_txtKullaniciAdiKeyTyped

    private void txtSifreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSifreKeyTyped
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_ENTER) {
            GirisYap();
        }
    }//GEN-LAST:event_txtSifreKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnKayit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtKullaniciAdi;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
