/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.gorsel.sinema.frm;

import com.gazi.gorsel.sinema.bll.CalisanBL;
import com.gazi.gorsel.sinema.bll.SatisBL;
import com.gazi.gorsel.sinema.model.Calisan;
import com.gazi.gorsel.sinema.model.TableModel;
import java.awt.HeadlessException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emin
 */
public class frmSatisListe extends javax.swing.JInternalFrame {

    SimpleDateFormat mf = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form frmSatisListe
     */
    public frmSatisListe() {
        initComponents();
    }

    void TabloDoldur() {
        SatisBL sbl = new SatisBL();
        DefaultTableModel dtm = (DefaultTableModel) tblList.getModel();
        for (int i = 0; i < dtm.getRowCount(); i++) {
            dtm.removeRow(i);
        }
        try {
            Date basTarih = dateBas.getDate();
            Date sonTarih = dateBit.getDate();
            String bas = mf.format(basTarih);
            String son = mf.format(sonTarih);
            if (sonTarih.before(basTarih)) {
                JOptionPane.showMessageDialog(null, "Bitiş tarihi başlangıç tarihinden önce olamaz.");
                return;
            }
            String ad = cmbCalisan.getSelectedItem().toString();
            List<TableModel> satisList = sbl.SatisListele(bas, son, ad);
            if (satisList == null || satisList.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Kayıt bulunamadı.");
                return;
            }
            Object rowData[] = new Object[6];
            for (int i = 0; i < satisList.size(); i++) {
                rowData[0] = satisList.get(i).getFilm();
                rowData[1] = satisList.get(i).getSalon();
                rowData[2] = satisList.get(i).getSeans();
                rowData[3] = satisList.get(i).getTutar();
                rowData[4] = satisList.get(i).getTarih();
                rowData[5] = satisList.get(i).getCalisan();
                dtm.addRow(rowData);
            }
        } catch (HeadlessException e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        pnlTop = new javax.swing.JPanel();
        dateBas = new org.jdesktop.swingx.JXDatePicker();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dateBit = new org.jdesktop.swingx.JXDatePicker();
        cmbCalisan = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnListele = new javax.swing.JButton();
        pnlBottom = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();

        setTitle("Satış Listele");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formİnternalFrameOpened(evt);
            }
        });

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        pnlTop.setBackground(new java.awt.Color(204, 255, 255));
        pnlTop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        pnlTop.add(dateBas, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 49, 137, -1));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Başlangıç");
        pnlTop.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel2.setText("Bitiş");
        pnlTop.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));
        pnlTop.add(dateBit, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 49, 126, -1));

        cmbCalisan.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cmbCalisan.setMaximumRowCount(100);
        cmbCalisan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tümü" }));
        pnlTop.add(cmbCalisan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 45, 111, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel3.setText("Çalışan");
        pnlTop.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 11, -1, -1));

        btnListele.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnListele.setText("Listele");
        btnListele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListeleActionPerformed(evt);
            }
        });
        pnlTop.add(btnListele, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 26, -1, -1));

        jSplitPane1.setTopComponent(pnlTop);

        pnlBottom.setLayout(new java.awt.BorderLayout());

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Film", "Salon", "Seans", "Tutar", "Tarih", "Çalışan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblList);
        if (tblList.getColumnModel().getColumnCount() > 0) {
            tblList.getColumnModel().getColumn(0).setResizable(false);
            tblList.getColumnModel().getColumn(1).setResizable(false);
            tblList.getColumnModel().getColumn(2).setResizable(false);
            tblList.getColumnModel().getColumn(3).setResizable(false);
            tblList.getColumnModel().getColumn(4).setResizable(false);
            tblList.getColumnModel().getColumn(5).setResizable(false);
        }

        pnlBottom.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(pnlBottom);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
        TabloDoldur();
    }//GEN-LAST:event_btnListeleActionPerformed

    private void formİnternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formİnternalFrameOpened
        dateBas.setDate(Date.from(Instant.now()));
        dateBit.setDate(Date.from(Instant.now()));
        CalisanBL cbl = new CalisanBL();
        List<Calisan> cList = cbl.CalisanListele();
        for (int i = 0; i < cList.size(); i++) {
            cmbCalisan.addItem(cList.get(i).getAd());
        }
    }//GEN-LAST:event_formİnternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListele;
    private javax.swing.JComboBox<String> cmbCalisan;
    private org.jdesktop.swingx.JXDatePicker dateBas;
    private org.jdesktop.swingx.JXDatePicker dateBit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlBottom;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JTable tblList;
    // End of variables declaration//GEN-END:variables
}
