/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.gorsel.sinema.frm;

import com.gazi.gorsel.sinema.bll.FilmBL;
import com.gazi.gorsel.sinema.bll.SalonBL;
import com.gazi.gorsel.sinema.bll.SeansBL;
import com.gazi.gorsel.sinema.model.Film;
import com.gazi.gorsel.sinema.model.Salon;
import com.gazi.gorsel.sinema.model.Seans;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author emin
 */
public class frmSatisYap extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmSatisYap
     */
    public frmSatisYap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        cmbFilm = new javax.swing.JComboBox<>();
        cmbSeans = new javax.swing.JComboBox<>();
        cmbSalon = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblAfis = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAciklama = new javax.swing.JTextArea();
        btnKoltukSec = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        datePicker = new org.jdesktop.swingx.JXDatePicker();

        setTitle("Satış");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formİnternalFrameOpened(evt);
            }
        });

        cmbFilm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbFilmİtemStateChanged(evt);
            }
        });

        jLabel1.setText("Film");

        jLabel2.setText("Seans");

        jLabel3.setText("Salon");

        lblAfis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtAciklama.setColumns(20);
        txtAciklama.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        txtAciklama.setLineWrap(true);
        txtAciklama.setRows(5);
        jScrollPane1.setViewportView(txtAciklama);

        btnKoltukSec.setText("Koltuk Seçimi");
        btnKoltukSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKoltukSecActionPerformed(evt);
            }
        });

        jLabel4.setText("Tarih");

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(23, 23, 23)))
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(datePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(cmbSeans, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbFilm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbSalon, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKoltukSec, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(lblAfis, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(664, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAfis, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbSeans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSalon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(datePicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKoltukSec)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        getContentPane().add(pnlMain, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formİnternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formİnternalFrameOpened
        FilmBL fbl = new FilmBL();
        SeansBL sbl = new SeansBL();
        SalonBL slbl = new SalonBL();
        List<Film> filmList = fbl.FilmListele();
        List<Seans> seansList = sbl.SeansListele();
        List<Salon> salonList = slbl.SalonListele();
        
        for (int i = 0; i < filmList.size(); i++) {
            cmbFilm.addItem(filmList.get(i).getAd());
        }
        for (int i = 0; i < seansList.size(); i++) {
            cmbSeans.addItem(seansList.get(i).getSaat());
        }
        for (int i = 0; i < salonList.size(); i++) {
            cmbSalon.addItem(salonList.get(i).getAd());
        }
        datePicker.setDate(Date.from(Instant.now()));
    }//GEN-LAST:event_formİnternalFrameOpened

    private void cmbFilmİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbFilmİtemStateChanged
        FilmBL fbl = new FilmBL();
        Film f = fbl.FilmGetir(cmbFilm.getSelectedItem().toString());
        lblAfis.setIcon(f.getAfis());
        txtAciklama.setText(f.getAciklama());
    }//GEN-LAST:event_cmbFilmİtemStateChanged

    private void btnKoltukSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKoltukSecActionPerformed
        if (datePicker.getDate().before(Date.from(Instant.now()))) {
            JOptionPane.showMessageDialog(null, "Geçmişe dönük seçim yapılamaz.");
            datePicker.setDate(Date.from(Instant.now()));
            return;
        }
        DateFormat myFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = datePicker.getDate();
        String dt = myFormat.format(date);
        SalonBL sbl = new SalonBL();
        FilmBL fbl = new FilmBL();
        SeansBL snsbl = new SeansBL();
        Salon s = sbl.SalonGetir(cmbSalon.getSelectedItem().toString());
        Seans sns = snsbl.SeansGetir(cmbSeans.getSelectedItem().toString());
        Film film = fbl.FilmGetir(cmbFilm.getSelectedItem().toString());
        frmKoltuk f = new frmKoltuk(dt, s, sns, film);
        pnlMain.add(f);
        f.setBounds(450, 0, 1000, 800);
        f.setVisible(true);
        f.setClosable(true);
    }//GEN-LAST:event_btnKoltukSecActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKoltukSec;
    private javax.swing.JComboBox<String> cmbFilm;
    private javax.swing.JComboBox<String> cmbSalon;
    private javax.swing.JComboBox<String> cmbSeans;
    private org.jdesktop.swingx.JXDatePicker datePicker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAfis;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JTextArea txtAciklama;
    // End of variables declaration//GEN-END:variables
}
