/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.gorsel.sinema.frm;

import com.gazi.gorsel.sinema.bll.SeansBL;
import com.gazi.gorsel.sinema.model.Seans;
import javax.swing.JOptionPane;

/**
 *
 * @author emin
 */
public class frmSeansEkle extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmSeansEkle
     */
    public frmSeansEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbSaat = new javax.swing.JComboBox<>();
        cmbDakika = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnKaydet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Seans Ekle");
        setMaximumSize(new java.awt.Dimension(820, 600));
        setMinimumSize(new java.awt.Dimension(820, 600));
        setPreferredSize(new java.awt.Dimension(820, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbSaat.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cmbSaat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09", "12", "15", "18", "21" }));
        getContentPane().add(cmbSaat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 71, 30));

        cmbDakika.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        cmbDakika.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "30" }));
        getContentPane().add(cmbDakika, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 77, 30));

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText(".");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 12, 30));

        btnKaydet.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 170, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/gorsel/sinema/img/seans.jpg"))); // NOI18N
        jLabel2.setText("Seans Ekle");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 801, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        String saat = cmbSaat.getSelectedItem().toString() + ":" + cmbDakika.getSelectedItem().toString();
        Seans s = new Seans();
        s.setSaat(saat);
        SeansBL sbl = new SeansBL();
        if (sbl.SeansKaydet(s) > 0) {
            JOptionPane.showMessageDialog(null, "Seans kayıt işlemi başarılı.");
        }
    }//GEN-LAST:event_btnKaydetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JComboBox<String> cmbDakika;
    private javax.swing.JComboBox<String> cmbSaat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
