/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gazi.gorsel.sinema.frm;

import com.gazi.gorsel.sinema.bll.YonetmenBL;
import com.gazi.gorsel.sinema.model.Yonetmen;
import javax.swing.JOptionPane;

/**
 *
 * @author emin
 */
public class frmYonetmenEkle extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmYonetmenEkle
     */
    public frmYonetmenEkle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAd = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setTitle("Yönetmen Ekle");
        setMaximumSize(new java.awt.Dimension(680, 500));
        setMinimumSize(new java.awt.Dimension(680, 500));
        setPreferredSize(new java.awt.Dimension(680, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Adı Soyadı");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 90, 30));

        txtAd.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        getContentPane().add(txtAd, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 170, -1));

        btnKaydet.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaydet, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 270, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gazi/gorsel/sinema/img/yonetmen.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        YonetmenBL ybl = new YonetmenBL();
        Yonetmen y = new Yonetmen();
        y.setAdSoyad(txtAd.getText().trim());
        if (ybl.YonetmenKayit(y) > 0) {
            JOptionPane.showMessageDialog(null, "Yeni yönetmen eklendi.");
            txtAd.setText("");
        }
    }//GEN-LAST:event_btnKaydetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKaydet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtAd;
    // End of variables declaration//GEN-END:variables
}
